import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from './utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children } : { children: React.ReactNode }) {
  
  const classes = cn(
    inter.className,
    'container max-w-6xl mx-auto'
  )

  return (
    <html lang="en">
      <body className={classes}>
        {children}
      </body>
    </html>
  )
}
